### ISSUE TITLE
Mint was created with a negative meaning of userId.

### ISSUE THREAD

**Issue by Romstreet13** [techbandorg/LA-Backend#86]
Steps to reproduce:

1. Send  request to endpoint: https://liqiudaccess-backend.herokuapp.com/api/mint/create

request:

{
    "merchantId": 1,
    "merchantName": "Netflix",
    "userId": -1,
    "userAddress": "0xa080c64e6a2937b327b50b75b408fbd5c739ff2b"
}

Асtual Result:  

  "id": 111,
    "nftId": 138,
    "merchantId": 1,
    "userId": -1,
    "userAddress": "0xa080c64e6a2937b327b50b75b408fbd5c739ff2b",
    "status": "success",
    "transactionHash": "0x8bb7bbdb1885ea0168abd1fb0a40c9f5df48be21d6cf318da752de8b3303e2df"

      200 ок

Expected Result: Error !

Attachment:

![Screenshot_2](https://user-images.githubusercontent.com/109031440/182857632-32a43a8c-2431-4931-a0ec-100238ca1a20.png)

**Comment by zAndrey95** [comment]
@itstoreall

**Comment by itstoreall** [comment]
fixed
@Romstreet13

**Comment by Romstreet13** [comment]
@zAndrey95 
Done

![Create mint - TEST - Google Chrome 2022-08-04 17 2](https://user-images.githubusercontent.com/109031440/182872891-7469161f-8234-4c72-9454-b821c240da9f.png)
