### ISSUE TITLE
Mail was added with a negative meaning of userId and merchantId.

### ISSUE THREAD

**Issue by Romstreet13** [techbandorg/LA-Backend#88]
**Steps to reproduce:**

Send request to endpoint: https://liqiudaccess-backend.herokuapp.com/api/mail/add

request:
{
    "merchantId": -1,
    "merchantName": "Test",
    "userId": "-1",
    "mail": "test@mail.com"
}

**Асtual Result:**
{
    "id": 18,
    "merchantId": -1,
    "merchantName": "Test",
    "userId": -1,
    "mail": "test@mail.com"
}

  200 ок

**Expected Result**: 
   Error !

**Attachment** :

![Add Mail - TEST - Google Chrome 2022-08-04 17 13 1](https://user-images.githubusercontent.com/109031440/182870545-ef04783d-e036-4509-9244-12df414c26bc.png)

**Comment by zAndrey95** [comment]
@itstoreall це пофікшено, так?

**Comment by itstoreall** [comment]
@zAndrey95 так, там зараз та валідаця що треба переробити на sequelize
